### ISSUE TITLE
farseek server crash 1.9.4

### ISSUE THREAD

**Issue by pikkon38** [delvr/Farseek#13] opened 2016-06-09 20:17 UTC
Trying to use farseek on my server causes it to crash 

http://pastebin.com/MLH8njGt

seems to work okay on clients.

**Comment by delvr** [comment] 2016-06-09 21:06
Thanks for reporting. This is a duplicate of #10 and will be fixed in the next release.

**Closed as completed by delvr** 2016-06-09 21:06 UTC
Labels: bug, duplicate
