### ISSUE TITLE
Crash on latest spongeforge

### ISSUE THREAD

**Issue by Tencao** [delvr/Farseek#43] opened 2018-07-22 08:29 UTC
Original issue with all relevant information - https://github.com/SpongePowered/SpongeForge/issues/2331

**Comment by Tencao** [comment] 2018-08-07 15:10
Any update on a fix for this issue?

**Comment by delvr** [comment] 2018-08-08 04:51
Hey Tencao, sorry for the delay on this one.

I assumed that the crash was due to Sponge changing the name of an internal method Farseek was using (as described in the linked Sponge issue), but I can't find any record in the Sponge source of that name actually changing. In fact, I was unable to reproduce the crash using the version of Sponge you were using. I tried adding Biomes'O'Plenty since it shows up in your stacktrace - still no crash.

Could you try again with only SpongeForge and Farseek/Streams/Repose and maybe BOP, and tell me if it still crashes? If not, we'll have to work to isolate the mod that triggers this.

**Comment by Tencao** [comment] 2018-08-09 04:30
I'll try again later today and report back any findings

**Comment by Rautherdir** [comment] 2018-09-27 21:36
While looking into this issue myself, I found that this is most likely a duplicate of https://github.com/Ordinastie/MalisisCore/issues/151
Adding MalisisCore to the list of mods mentioned above causes this issue to appear.

**Comment by delvr** [comment] 2018-10-12 06:46
Thanks @Rautherdir  for the update! I tested and confirmed that the crash only happens when MalisisCore is present. I'll close this issue; if the MalisisCore devs fix the issue on their end and then Farseek still crashes with their new version we'll re-open this.

**Closed as completed by delvr** 2018-10-12 06:46 UTC
Labels: compatibility
