### ISSUE TITLE
I've been reporting this to Fancy Fluid Storage (lordmau5) ...

### ISSUE THREAD

**Issue by kreezxil** [delvr/Farseek#11] opened 2016-06-05 19:26 UTC
And he keeps insisting it is your mod that is causing the issue. Here is my latest report on the issue.

I updated to build 1954 of forge today and got the error back, disregard if the dev hasn't been made public yet or not, your choice. :)

Issue: fancy-fluid-storage-1.9.4-1.6.0-b19 crashes dedicated Forge 1.9.4 build 1954 on startup

https://gist.github.com/51f0547d87b7a65e8ed5afe56e9cd911

https://gist.github.com/93e9572d1436b6c6493f0039e7cc1237

Here is the thread he locked because he doesn't want to deal with it any longer:
https://github.com/Lordmau5/FFS/issues/55#issuecomment-223831766

**Comment by llavigne-localytics** [comment] 2016-06-05 19:50
Hi kreezxil, there was an issue opened here from this thread (#10). It's something that can be fixed in either mod but it's simpler on the farseek side so it'll be fixed in the next version in a few days.

**Comment by kreezxil** [comment] 2016-06-05 20:01
Thanks. :)

**Comment by delvr** [comment] 2016-06-06 15:15
Hi kreezxil, there was an issue opened here from that thread (#10). It's something that can be fixed in either mod but it's simpler on the Farseek side so it'll be fixed in the next version in a few days.

Closing as duplicate of #10.

**Closed as completed by delvr** 2016-06-06 15:15 UTC
Labels: bug, duplicate

**Comment by kreezxil** [comment] 2016-06-12 22:48
It's been more than a few days, have you built the patch yet, the other mod pack doesn't want to even address the issue which is really odd.

There is another mod, Forestry, which also says the following issue is all you.

Issue:  forestry-1.9.4-5.0.12.149 crashes dedicated Forge 1.9.4 build 1960 on startup

crash report:
https://gist.github.com/2f73c23bd5be99b476192b0b0d88bff5

fml server latest:
https://gist.github.com/8fb3ac6e59d6697b61f670899c9ded11

**Comment by kreezxil** [comment] 2016-06-12 22:48
I've reported it to them too.

**Comment by kreezxil** [comment] 2016-06-12 22:50
It's a loss for them tho, I really love your streams and have rafted at least three rivers so far, the other mods, I remove them from my pack.

Btw, I may have suggested this before, but in case I have not.

I'd like to see you add an item, the rubber raft. Its feature being that you can't steer it and it bounces off the sides of things. You could have it crafted from oredicted rubber balls.
