### ISSUE TITLE
Client Crash - java.lang.ClassCastException: net.minecraft.util.math.ChunkPos cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by ProsperCraft** [delvr/Farseek#37] opened 2018-04-03 02:17 UTC
https://gist.github.com/ProsperCraft/995db1b2c8deb8cb3e5eb31d272dd7b4

I created a new world, started running around, and then crashed.

**Comment by delvr** [comment] 2018-04-03 07:56
This is caused by an internal change in Forge 1.12.2-14.23.2.2652. I will release a fix in the next few days, meanwhile please use Forge 1.12.2-14.23.2.2651 or earlier. Thanks!

**Comment by Darkosto** [comment] 2018-04-05 16:36
Glad I happened to see this! I'll wait on my SevTech update until this one is ready. Thanks for looking at this!

**Comment by delvr** [comment] 2018-04-05 19:56
Fixed in Farseek 2.2.5.

**Closed as completed by delvr** 2018-04-05 19:56 UTC
Labels: bug, 1.12
