### ISSUE TITLE
Farseek crashing server by taking too long

### ISSUE THREAD

**Issue by kreezxil** [delvr/Farseek#46] opened 2019-04-14 15:15 UTC
Happening under FORGE build 2825.

farseek 1.12-2.3.1

server crash reports:
http://paste.ubuntu.com/p/rtbDYh3bKk/
http://paste.ubuntu.com/p/vMyHHsfzYW/
http://paste.ubuntu.com/p/nXGNVFp3mp/
http://paste.ubuntu.com/p/mMvd3Fgc22/
http://paste.ubuntu.com/p/YTWTKTqChv/
http://paste.ubuntu.com/p/SDgNPsCPHD/
http://paste.ubuntu.com/p/JTTVsxK7Fx/
http://paste.ubuntu.com/p/ZnnjcNPkT3/
http://paste.ubuntu.com/p/ztGmvxMk5p/

my max tick time is set to 240000 and it's still not enough, is there an option to allow streams to gracefully give up instead of allowing them to hang a server?

**Comment by delvr** [comment] 2019-04-15 21:59
Hi Kreezxil, thanks for reporting this. I haven't been able to reproduce this issue with that Forge build (or any other), so it's probably a conflict with another mod. The only non-Farseek mod I see in the actual crash log is LagBGonReborn, which seems to be in the process of loading a chunk to perform an overcrowding check. I don't have a crowded enough server to reproduce this, but could you try again without LagBGonReborn and see if it still happens? Thanks!

**Comment by kreezxil** [comment] 2019-04-16 14:07
I took lagbgone out for other reasons, but it does appear to be not
happening.

**Comment by delvr** [comment] 2019-05-05 21:29
I'll close this issue for now and track ServerHangWatchdog timeouts in [this Streams issue](https://github.com/delvr/Streams/issues/74).

**Closed as completed by delvr** 2019-05-05 21:29 UTC
Labels: performance
